/**
 List of assets and their relative locations to preload in main.js
 */
ASSET_LIST = 
[
    WORLD_BATTLEFIELD = 'model/battlefield/battlefield.dae',
    WORLD_CASTLE = 'model/castle/castle.dae',
    WORLD_HFIELD = 'model/hfield/hfield.dae',
    WORLD_GROUND3 = 'model/ground3/ground3.dae',
    MODEL_PATH = 'model/asuka/Asuka.pmd',
    MODEL_REI_PATH = 'model/rei/Rei.pmd',
    MOTION_PATH = 'motion/walk.vmd',
    MOTION_JUMP_PATH = 'motion/jumpfix2.vmd',
    MOTION_TEST = 'motion/everybody.vmd',
    TEXTURE_SKYDOME = 'images/skydome.jpg',
    MODEL_CHEN = 'model/chen/chenfix.pmd',
    MODEL_RAN = 'model/ran/ran.pmd',
    MODEL_HOLO = 'model/holo/holofix.pmd',
    MODEL_HONK = 'model/honk/honk.dae',
    TEX_CROSSHAIRS = 'images/crosshairs.png',
    TEX_CROSSHAIRS2 = 'images/crosshairs2.png',
    TEX_CROSSHAIRS2RED = 'images/crosshairs2red.png',
    TEX_GRASS = 'images/grass.jpg',
    TEX_METAL = 'images/metal.jpg',
    TEX_CIRCLE_WHITE = 'images/whitecircle.png',
    TEX_HEALTH = 'images/health.png',
    TEX_TREE = 'images/tree.png',
    MUSIC_CORNERIA = 'sounds/corneria.mp3',
    MUSIC_BOSS = 'sounds/boss.mp3',
    MUSIC_VICTORY = 'sounds/victory.mp3',
    SOUND_LASER = 'sounds/laser_single.mp3',
    SOUND_EXPLODE = 'sounds/exp.mp3',
    SOUND_BIGEXPLODE = 'sounds/bigexplode.mp3',
    SOUND_HIT = 'sounds/expSm.wav',
    SOUND_TARGET = 'sounds/target.mp3',
    SOUND_TARGETLOCK = 'sounds/targetLock.mp3',
    SOUND_CHARGELASER = 'sounds/chargeLaser.mp3',
    SOUND_BEAM = 'sounds/beamRifle.wav',
    SOUND_CHARGELASEREXPLODE = 'sounds/chargeLaserExplode.mp3',
    SOUND_RADIOSTART = 'sounds/radioStart.mp3',
    SOUND_RADIOEND = 'sounds/radioEnd.mp3',
    SOUND_LOADHEALTH = 'sounds/loadhealth.mp3',
    SOUND_HONK = 'sounds/honk.mp3',
    MODEL_TEST = 'model/modeltest2.dae',
    MODEL_YUKKURI = 'model/reimuyukkuri/reimuyukkuribig.pmd',
    MODEL_TREE = 'model/tree/tree.dae',
    SPRITE_RAN = 'images/ran.png',
    'images/tex.jpg',
    'images/tex.png',
    'images/soccerball.png', 
    'sounds/tielaser.wav', 
    'sounds/explode.wav', 
    'images/cockpit.png'
];

